Задания и исполнители
htmlacademy-yii/414045-task-force-1 pull request #10
Opened 2021-08-01 20:16 UTC by Archer039

2021-08-02 13:10 UTC, mihan007 requested changes
Какие-то получились адские отступы и весь код стал выглядеть странно. Давай вернемся к чистому PSR-12. Вот видео про него https://mihan007.notion.site/1-d1a3ee1c3c924237951fb0d456e85315

Это позволит в следующих PR мне проверять не 124 файла, а намного меньше

2021-08-03 13:33 UTC, mihan007 requested changes
Смотри - у меня опять замечания по code style. Что не нравится
1. Конкатенация через `.` идет без пробелов, надо с ними
2. Переносы строк очень странные. В `<?php` и других местах, по коду комменты
3. Аналогично с отступами - кажется, что некоторые из них избыточны

Посмотри, пожалуйста.

2021-08-03 13:33 UTC, mihan007 commented on backend/views/layouts/blank.php
>      <title><?= Html::encode($this->title) ?></title>
- я советую вытащить `Html::encode` в функцию попроще типа
```
function e($string) {
  return Html::encode($string)
}
```
- это нужно, чтобы уменьшить объем кода и сделать его визуально проще

2021-08-03 13:33 UTC, mihan007 commented on backend/views/layouts/main.php
> +$this->beginPage() ?>
это не должно переноситься. `<?php $this->beginPage() ?>` должно быть на одной строке. и все остальное похожее тоже надо поправить

2021-08-03 13:33 UTC, mihan007 commented on backend/views/layouts/main.php
> +                                    'links' => isset($this->params['breadcrumbs'])
я не знаю насчет этого отступа. выглядит громоздко. Но если это ок с точки зрения PSR, то мне ок.

2021-08-03 13:33 UTC, mihan007 commented on backend/views/site/error.php
> +        The above error occurred while the Web server was processing your
выглядит как будто у тебя в настройка реформата стоит ограничение "переноси строки, если они длиннее 80 символов". 80 символов было актуально для старых мониторов. сейчас надо ограничение в 120 символов. я не уверен на 100%, что это можно настроить, но надо посмотреть. Большого смысла в этих переносах нет.

2021-08-03 13:33 UTC, mihan007 commented on common/config/main.php
> +    'vendorPath' => dirname(dirname(__DIR__)).'/vendor',
везде. оператор конкатенации точка должна обрамляться слева и справа пробелом. это по PSR. 
- см. 6.2. Binary operators в https://www.php-fig.org/psr/psr-12/#62-binary-operators
- https://stackoverflow.com/questions/66033175/php-psr-whitespaces-before-and-after-concatenate-operator-question-dot

у меня оно так и работает. сейчас выглядит, что у тебя в IDE установлен PSR-12 и еще сам сверху накрутил. не надо)

2021-08-03 13:33 UTC, mihan007 commented on common/mail/layouts/text.php
> +$this->beginPage() ?>
лишний перенос. еще раз акцентирую - везде поправить

2021-08-03 13:33 UTC, mihan007 commented on common/widgets/Alert.php
> +                                                      'body' => $message,
очень гигантские отступы. что-то не так с ними

2021-08-03 13:33 UTC, mihan007 commented on console/migrations/m210726_084321_add_created_at_column_updated_at_column_to_categories_table.php
> +    Migration
непонятно зачем тут перенос. скорее всего из-за ограничения в 80 символов. так не надо, некрасиво. там можно отключить. есть опция "wrap if long", для имен классов это не надо

2021-08-03 13:33 UTC, mihan007 commented on frontend/controllers/TasksController.php
> +        $tasks = Task::find()->where(
сделано верно.

2021-08-03 13:33 UTC, mihan007 commented on frontend/controllers/UsersController.php
> +        return $this->render('index', ['users' => $users]);
`['users' => $users]` можно записать короче как `compact($users)`

2021-08-03 13:33 UTC, mihan007 commented on Сomponents/Time/TimeDifferent.php
> +    public function getDif(): DateInterval|bool
getDif**f**

2021-08-03 13:33 UTC, mihan007 commented on Сomponents/Time/TimeDifferent.php
> +class TimeDifferent extends Time
по названию попридираюсь. класс обычно называют существительным. То есть тут хорошо бы использовать не Different, а Difference

2021-08-03 13:33 UTC, mihan007 commented on Сomponents/Time/TimeNumEnding.php
> +            $ending = match ($i) {
match - прям по красоте, лайк

2021-08-03 13:33 UTC, mihan007 commented on Сomponents/Exceptions/TimeException.php
> +class TimeException extends BaseException
а ты где-то его бросаешь? не заметил

2021-08-03 13:33 UTC, mihan007 commented on frontend/models/User.php
> +            return $this->hasMany(Review::class, ['sender_id' => 'id']);
красиво сделал, нравится

2021-08-08 11:49 UTC, Archer039 commented on frontend/controllers/UsersController.php
> +        return $this->render('index', ['users' => $users]);
Супер, так намного удобнее)

2021-08-08 11:49 UTC, Archer039 commented on console/migrations/m210726_084321_add_created_at_column_updated_at_column_to_categories_table.php
> +    Migration
Да, но я на 80 не менял) стоит 120. Поправил вручную

2021-08-08 12:02 UTC, Archer039 commented on Сomponents/Exceptions/TimeException.php
> +class TimeException extends BaseException
Я пока писал, где-то его применял, потом мне код не понравился, я рефакторил и он оказался не нужен, оставил на будущее

2021-08-09 05:38 UTC, mihan007 requested changes
Привет! Будем дорабатывать.

1. Желательно. Поправить форматирование кода. У тебя очень сильные отступы и насильно переносится [. Вариант слева, до изменений, в большинстве случаев выглядит компактнее. Тут тебе решать
2. Обязательно. При запуске кода увидел
![2021-08-09 at 07 52](https://user-images.githubusercontent.com/939122/128661673-08a2313b-45ea-4f4e-ade2-5c66274567c4.png)
Рекомендую
![2021-08-09 at 07 54](https://user-images.githubusercontent.com/939122/128661889-69481c6c-03ce-4083-8f80-386454de7faf.png)
** Пункт 4 - лучше в другом месте **
![2021-08-09 at 07 59](https://user-images.githubusercontent.com/939122/128661974-59499cb0-6460-41e1-b130-4a58a04b99ec.png)
3. Желательно. ссылки в верхнем меню уже должны быть корректными, сейчас они ведут на верстку - заглушку
![2021-08-09 at 08 04](https://user-images.githubusercontent.com/939122/128662229-574f3d30-644b-4536-a5d3-0be186d695d4.png)
смотри https://www.yiiframework.com/doc/guide/2.0/en/runtime-routing#creating-urls
4. Желательно. Сейчас проверять неудобно - обычно базу перед проверкой я всегда наливаю с нуля через `yii migrate/fresh`. Тут же приходится очищать базу - заливать ее через scheme.sql, а потом уже миграции. было бы удобнее, чтобы была самая-самая первая миграция, которая зальет scheme.sql. см https://yiiframework.ru/forum/viewtopic.php?t=31209
5. Желательно. Было бы классно наливать базу из файлов в `sqlExportData` через консольную команду. Например, назвали бы ее `yii db/seed`. См. https://elisdn.ru/blog/50/console-commands-in-yii
6. Желательно. created_at и updated_at можно заполнять автоматически самой базой. Посмотри CURRENT_TIMESTAMP
7. Обязательно. Список новых задач пустой. Я понимаю, что это проблема данных. Но надо их доделать, чтобы страница была непустой. Даты поменять. Как раз в рамках пункта 5 выше можно поменять будет дату создания задач в tasks.sql и заново залить их в базу
![2021-08-09 at 08 21](https://user-images.githubusercontent.com/939122/128663301-3fbe2130-d053-40ad-8596-b5a8c1a44403.png)
8. Обязательно. На этой же странице надо добавить кейс, когда задач нет. Я бы добавил надпись "Новых задач нет".
9. Обязательно. По тз на странице заданий "опубликованные задания, на которые еще не нашёлся исполнитель". Я у одной из задач убрал исполнителя в базе и страница осталась пустой. Это неверно. Сортировку тоже проверь как поправишь
![2021-08-09 at 08 36](https://user-images.githubusercontent.com/939122/128664039-a7420032-e2a0-4266-9649-05a5959217a7.png)
9. Мощь. Сделать вывод списка задач через ListView, https://www.yiiframework.com/doc/guide/2.0/ru/output-data-widgets#list-view и https://xn--d1acnqm.xn--j1amh/%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B8/yii-2-%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B5%D0%B9-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-%D0%B2%D0%B8%D0%B4%D0%B6%D0%B5%D1%82%D0%B0-listview-%D0%BF%D0%BE%D0%B4%D1%80%D0%BE%D0%B1%D0%BD%D1%8B%D0%B9-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80
10. Желательно. Пока на главной странице сайта ничего полезного нет - открываешь и пустота. Я бы сделал редирект на страницу новых заданий.
11. Обязательно. По ТЗ "Исполнители отсортированны от свежих регистраций к старым". Сейчас я этого не увидел. Вот сортировка в базе по дате создания
![2021-08-09 at 08 32](https://user-images.githubusercontent.com/939122/128663798-c51d1465-bab7-4cd6-ab8a-a6e056438bbc.png)
- Boonie должна быть первой на странице
- А сейчас первая Karrie Buttress
![2021-08-09 at 08 33](https://user-images.githubusercontent.com/939122/128663863-9dea79e5-f865-432b-8eed-4edafa7dc9aa.png)
12. Мощь - список исполнителей через ListView
13. Желательно. Если аватара пользователя пустая, то вместо некрасивого квадратика без картинки выводить какую-то универсальную иконку.

2021-08-09 06:55 UTC, Archer039 commented on frontend/views/tasks/index.php
> +        <?php
Это уже понял, везде поправлял, тут упустил

2021-08-15 13:45 UTC, Archer039 commented on backend/views/layouts/main.php
> +use common\widgets\Alert;
Хороший вопрос... я туда вообще не зализал ещё, это пока с реформатом разбирался видимо случайно Optimize imports забыл вырубить...)

2021-08-15 13:47 UTC, Archer039 commented on common/widgets/Alert.php
> +                                'id' => $this->getId() . '-' . $type
Наконец нашёл из-за чего такие отступы...

2021-08-15 13:50 UTC, Archer039 commented on frontend/models/Task.php
> +        $timeDif = new TimeDifference($this->created_at);
Поправил

2021-08-16 06:04 UTC, mihan007 requested changes
Скоро зафиналим. Меня больше всего напряг редирект в view и дублирование кода для поиска задач в двух view. Остальное мелочи. Поправь, пожалуйста.

Еще раз повторюсь - никакой бизнес логики, никаких редиректов в view. Только логика отображения - циклы, if и вызов функций, которые возвращают строку или объект для дальнейшей выдачи. Место логики и редиректов в других местах.

2021-08-16 06:04 UTC, mihan007 commented on frontend/views/tasks/index.php
> +<section class="search-task">
вытащи в отдельный view и подключи через renderPartial

2021-08-16 06:04 UTC, mihan007 commented on frontend/views/users/index.php
> +<section class="search-task">
и, кстати, ты сверху будешь вытаскивать кусок view. это же такой-же? будет классно тут просто переиспользовать вынесенный код

2021-08-16 06:04 UTC, mihan007 commented on Сomponents/Routes/Route.php
> +class Route
отличное решение

2021-08-16 06:40 UTC, Archer039 commented on backend/views/layouts/main.php
> +use common\widgets\Alert;
Он в коде используется

2021-08-16 11:08 UTC, Archer039 commented on common/helpers/stringHelper.php
> +function encode($string): string
Сделал

2021-08-16 11:09 UTC, Archer039 commented on common/config/bootstrap.php
> +require_once __DIR__ . '/../helpers/helpers.php';
Ну раз уж сделал, оставим как есть)

2021-08-16 11:09 UTC, Archer039 commented on common/helpers/stringHelper.php
> +}
Ок

2021-08-16 11:09 UTC, Archer039 commented on console/controllers/SeedController.php
> +                        exit;
Поправил, буду знать)

2021-08-16 11:09 UTC, Archer039 commented on console/controllers/SeedController.php
> +                exit;
Убрал

2021-08-16 11:10 UTC, Archer039 commented on frontend/views/site/index.php
> +Yii::$app->getResponse()->redirect(\Components\Routes\Route::getTasks());
Перенёс в контроллер

2021-08-16 11:11 UTC, Archer039 commented on frontend/views/tasks/index.php
> +<section class="search-task">
Они разные, там только самый первый блок с категориями одинаковый вначале, дальше разные

2021-08-16 12:28 UTC, merged