6.5.  Тайные тропы
htmlacademy-yii/414045-task-force-1 pull request #12
Opened 2021-09-15 13:35 UTC by Archer039

2021-09-16 04:56 UTC, olegmifle requested changes

2021-09-16 04:56 UTC, olegmifle commented on common/models/User.php
> + * UserHelper model
Зачем поменял?

2021-09-16 04:56 UTC, olegmifle commented on frontend/controllers/TasksController.php
> +    private function getTaskDataProvider(TaskFilter $filter): ActiveDataProvider
Почему бы не унести этот "хлепер" в модель и оттуда получать готовые данные?

2021-09-16 04:56 UTC, olegmifle commented on frontend/controllers/TasksController.php
> +    public function actionView(int $id = null): string
Предлагаю `getViewAction` - вначале идёт метод, которым запрашивается роут, потом названия контроллера, потом потсфикс Action. Так, если у тебя будет обновление задачи, ты сможешь назвать postTaskAction.

2021-09-16 04:56 UTC, olegmifle commented on frontend/controllers/TasksController.php
> +        if (!$id || !Task::findOne($id)) {
Неявных приведений лучше избегать. Если ты хочешь проверить на null, то так и проверяй.
Task::findOne($id) - 2 раза запрашиваешь тут и ниже. Зачем?

2021-09-16 04:56 UTC, olegmifle commented on frontend/controllers/TasksController.php
> +                'categoryClassName'));
Чёт как-то разнесло аргументы) Попробуй написать это более читаемо, пожалуйста.

2021-09-16 04:56 UTC, olegmifle commented on frontend/controllers/TasksController.php
> +            ->leftJoin(['u' => 'users'], 'u.id = responses.user_id');
Унеси это в модель плз, из контроллера дёргай уже готовый метод. А то логика расползается по проекту.

2021-09-16 04:56 UTC, olegmifle commented on frontend/controllers/TasksController.php
> +                'pageSize' => 5,
Вынеси `5` в константу класса, в коде не должно быть магических чисел

2021-09-16 04:56 UTC, olegmifle commented on frontend/controllers/UsersController.php
> +        }
Тут замечания те же самые.

2021-09-16 04:56 UTC, olegmifle commented on frontend/views/tasks/_responsesList.php
> +    <a href="<?= \Components\Routes\Route::getUserView($model['user_id']) ?>"><img src="<?= $model['avatar_src'] ?? UserConstants::USER_DEFAULT_AVATAR_SRC ?>" width="55" height="55"></a>
Импортируй через use неймспейс.

2021-09-16 04:56 UTC, olegmifle commented on frontend/views/tasks/_taskList.php
> +    <a href="tasks/view/<?= $model->id ?>" class="link-regular">
У тебя в одном месте массив, в другом объект. Не получится к единому типу привести?

2021-09-16 04:56 UTC, olegmifle commented on frontend/views/tasks/index.php
> +            'itemView' => '_taskList',
А зачем подчёркивание?

2021-09-16 04:56 UTC, olegmifle commented on Сomponents/Constants/CategoryConstants.php
> +class CategoryConstants
А зачем этот класс?

2021-09-17 14:00 UTC, Archer039 commented on common/models/User.php
> + * UserHelper model
Не заметил, это у меня шторм похоже поменял при рефакторе... Поправил)

2021-09-18 13:35 UTC, Archer039 commented on frontend/controllers/TasksController.php
> +    private function getTaskDataProvider(TaskFilter $filter): ActiveDataProvider
Перенёс, и по аналогии другие DataProvider так-же в модели.

2021-09-18 15:02 UTC, Archer039 commented on frontend/controllers/TasksController.php
> +    public function actionView(int $id = null): string
А точно именно в таком порядке? В yii же action должно префиксом идти... Или создать "отдельное действие" и регистрировать его в actions() контроллера?

2021-09-18 15:11 UTC, Archer039 commented on frontend/controllers/TasksController.php
> +        if (!$id || !Task::findOne($id)) {
Понял. По Task::findOne($id), да как-то просмотрел...

2021-09-18 15:13 UTC, Archer039 commented on frontend/controllers/TasksController.php
> +                'categoryClassName'));
Поправил

2021-09-18 15:14 UTC, Archer039 commented on frontend/controllers/TasksController.php
> +            ->leftJoin(['u' => 'users'], 'u.id = responses.user_id');
Перенёс в модель

2021-09-18 15:20 UTC, Archer039 commented on frontend/controllers/TasksController.php
> +                'pageSize' => 5,
Строки уже привык уносить в константы, а вот числа ещё нет) Поправил

2021-09-18 15:31 UTC, Archer039 commented on frontend/controllers/UsersController.php
> +        }
Поправил

2021-09-18 15:32 UTC, Archer039 commented on frontend/views/tasks/_responsesList.php
> +    <a href="<?= \Components\Routes\Route::getUserView($model['user_id']) ?>"><img src="<?= $model['avatar_src'] ?? UserConstants::USER_DEFAULT_AVATAR_SRC ?>" width="55" height="55"></a>
Как-то пропустил... Поправил

2021-09-18 16:01 UTC, Archer039 commented on frontend/views/tasks/_taskList.php
> +    <a href="tasks/view/<?= $model->id ?>" class="link-regular">
Да, что-то я там затупил)

2021-09-18 16:02 UTC, Archer039 commented on frontend/views/tasks/_taskList.php
> +    <a href="tasks/view/<?= $model->id ?>" class="link-regular">
Переделал на объекты

2021-09-18 16:03 UTC, Archer039 commented on frontend/views/tasks/index.php
> +            'itemView' => '_taskList',
Чтобы отделить шаблоны с DataProvider и пагинацией от шаблонов для действий

2021-09-18 16:05 UTC, Archer039 commented on Сomponents/Constants/CategoryConstants.php
> +class CategoryConstants
Это в каком-то из первых заданий нужно было создать класс с картой имён, для пользователя и внутренних названий.

2021-09-19 12:31 UTC, olegmifle commented on frontend/controllers/TasksController.php
> +    public function actionView(int $id = null): string
Если по простому не получается, то можно не мудрить)

2021-09-19 12:33 UTC, olegmifle commented on frontend/views/tasks/index.php
> +            'itemView' => '_taskList',
Кажется лишним. Легко можно гле-то это забыть сделать.

2021-09-19 12:34 UTC, merged