7.5. Стой! Кто идёт?!
htmlacademy-yii/414045-task-force-1 pull request #14
Opened 2021-09-29 10:27 UTC by Archer039

2021-09-30 04:47 UTC, olegmifle requested changes

2021-09-30 04:47 UTC, olegmifle commented on frontend/models/User.php
> +final class User extends ActiveRecord implements IdentityInterface
А зачем тебе имплементить интерфейс, если половину методов ты не реализуешь?

2021-09-30 04:47 UTC, olegmifle commented on frontend/controllers/SiteController.php
> +                \Yii::$app->user->login($user);
У тебя логин в 2х местах происходит. Получится ли вынести логику в общий метод?

2021-10-01 15:14 UTC, Archer039 commented on frontend/models/User.php
> +final class User extends ActiveRecord implements IdentityInterface
Это так в учебнике было) Не подумал... На будущее если используются не все методы интерфейса, лучше его не реализовывать?

2021-10-01 15:27 UTC, Archer039 commented on frontend/models/User.php
> +final class User extends ActiveRecord implements IdentityInterface
Компонент WebUser требует реализацию интерфейса IdentityInterface. Я как-то не нашёл другого способа, сделал как в учебнике) Как ещё это можно сделать?

2021-10-01 15:27 UTC, Archer039 commented on frontend/controllers/SiteController.php
> +                \Yii::$app->user->login($user);
Да, тут он лишний, забыл про него. SiteController почистил от ненужных методов.

2021-10-03 08:47 UTC, merged