Армия моделей
htmlacademy-yii/414045-task-force-1 pull request #9
Opened 2021-07-24 22:18 UTC by Archer039

2021-07-25 05:08 UTC, mihan007 requested changes
1. Включи автоформат по PSR при коммите 
2. Лучше валидаторы проработать уже сейчас. Ты сам знаешь о типах данных в полях намного больше чем Gii. Опираясь на эти знания, доработай валидаторы https://www.yiiframework.com/doc/guide/2.0/en/tutorial-core-validators. Чем качественнее они будут, тем меньше ошибок будет при работе с моделями. А это ключевые сущности системы и они должны быть максимально корректными.

2021-07-25 05:08 UTC, mihan007 commented on frontend/models/Task.php
> +            [['customer_id', 'title', 'category_id', 'state', 'price'], 'required'],
На поле price нужен валидатор

2021-07-25 05:08 UTC, mihan007 commented on frontend/models/User.php
> + * @property Review[] $reviews0
?

2021-07-25 05:08 UTC, mihan007 commented on frontend/models/User.php
> + * @property Task[] $tasks0
?

2021-07-25 05:08 UTC, mihan007 commented on frontend/models/User.php
> + * @property Message[] $messages0
?

2021-07-25 05:08 UTC, mihan007 commented on frontend/models/User.php
> +            [['role', 'city_id', 'rating'], 'integer'],
role - валидатор in

2021-07-25 05:08 UTC, mihan007 commented on frontend/models/User.php
> +            [['name', 'email', 'password', 'city_id'], 'required'],
На rating тоже можно либо in, либо integer с min/max

2021-07-25 05:08 UTC, mihan007 commented on frontend/models/User.php
> +            [['birthday', 'created_at', 'updated_at'], 'safe'],
- валидировать datetime
- валидировать email

2021-07-25 05:08 UTC, mihan007 commented on frontend/models/UsersSpecialty.php
> +            [['categoriy_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::class, 'targetAttribute' => ['categoriy_id' => 'id']],
Имя поля странное. Опечатка при создании базы?

2021-07-25 08:39 UTC, Archer039 commented on frontend/models/User.php
> + * @property Message[] $messages0
Думал gii лучше знает)) поэтому не трогал

2021-07-25 10:32 UTC, Archer039 commented on frontend/models/UsersSpecialty.php
> +            [['categoriy_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::class, 'targetAttribute' => ['categoriy_id' => 'id']],
Да, опечатка

2021-07-26 04:30 UTC, mihan007 requested changes
К успеху идем. Еще чуть-чуть, еще немного!

1. created_at, updated_at должны быть консистенты - либо везде быть, либо нет. я бы везде добавил. это нужно, чтобы последующий код мог на них рассчитывать. если в части моделей их нет, то программист будет каждый раз ходить в модель и смотреть есть ли, например, created_at. это время. проще везде добавить и полагаться на этот факт.
2. на них же везде надо навесить валидатор datetime. да, в подавляющем большинстве случаев это поле фреймворк заполнит автоматически. но человек тоже может их заполнить. пусть тогда не ошибается и, если ошибется, то его остановить валидатор, а не exception при сохранении в БД.
3. посмотреть на несколько валидаторов одного поля в рамках модели. скорее всего нужен только один валидатор, остальные избыточны. это некритично, но надо понимать. тут принцип минимализма - если у тебя задачу валидации решает один валидатор, то зачем другие? выбор валидатора надо делать по принципу "самый строгий". например, если у тебя на поле валидаторы `integer` и `boolean`, то оставляем `boolean`, так как с ним у тебя наименьшее верное значение поля. `exist_at` строже остальных, например.

2021-07-26 04:30 UTC, mihan007 commented on frontend/controllers/TestModelController.php
> +        ) {
что-то тут явно пошло не так) закрывающую скобку надо на ту же строку, где и условие

2021-07-26 04:30 UTC, mihan007 commented on frontend/models/Response.php
> +            [['content', 'created_at', 'updated_at'], 'safe'],
created_at, updated_at - валидатор datetime?

2021-07-26 04:30 UTC, mihan007 commented on frontend/models/Review.php
> +            [['created_at'], 'safe'],
валидатор datetime?

2021-07-26 04:30 UTC, mihan007 commented on frontend/models/TaskAttachment.php
> +class TaskAttachment extends ActiveRecord
у тебя в других моделях есть created_at, updated_at. Это полезные поля, которые мы будем заполнять автоматически. Я бы их все добавил во все таблицы, кроме вспомогательных. Вспомогательные - это те, что используются для связи многие-ко-многим.

2021-07-26 04:30 UTC, mihan007 commented on frontend/models/User.php
> +            [['created_at', 'updated_at'], 'datetime'],
во! тут как надо

2021-07-26 04:30 UTC, mihan007 commented on frontend/models/UserSetting.php
> +                'integer',
для этих аттрибутов можно оставить только валидатор boolean. нет смысла проверять и integer, и boolean

2021-07-26 04:30 UTC, mihan007 commented on frontend/models/UserSetting.php
> +                    'user_id',
только это можно integer оставить. да и то необязательно, так как у тебя уже есть условие для проверки, что это поле является id другой таблицы. то есть можно оставить только `exist` и все будет ок.

2021-07-26 09:26 UTC, Archer039 commented on frontend/controllers/TestModelController.php
> +        ) {
Да, просмотрел я.. и автоформат не поправил(

2021-07-26 13:48 UTC, mihan007 reviewed
через годы, через расстояния))

я тебя утомлю, но лучше сейчас, чем в проде. phpdoc посмотри внимательно - где-то пропущены property, которые отражают relation. где-то тип property неверный - указано, что возвращается одна модель, а по факту вернется массив моделей.

кстати, массив моделей и вообще массив объектов часто называют коллекцией. не удивляйся, если у меня это услышишь или прочитаешь. я в свое время не мог воткнуть в слова техлида. "коллекция? шо за коллекция, если это массив"))

2021-07-26 13:48 UTC, mihan007 commented on frontend/models/Category.php
> + * @property string|null $updated_at
а где же свойства для $tasks и $userSpecialities?

2021-07-26 13:48 UTC, mihan007 commented on frontend/models/City.php
> + * @property string $updated_at
Task[] $tasks;
User[] $users;

2021-07-26 13:48 UTC, mihan007 commented on frontend/models/Message.php
> + * @property User $sender
во, тут как надо!

2021-07-26 13:48 UTC, mihan007 commented on frontend/models/User.php
> + * @property Message $messages
тут и ниже у тебя проперти возвращает массив, а не один объект. то есть
- неверно `@property Message $messages`
- верно `@property Message[] $messages`

2021-07-27 11:48 UTC, mihan007 approved these changes
Добил! Прекрасно!

2021-07-27 11:48 UTC, merged